---

- name: Updating all packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes


- name: Installing services using apt
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ apt_package_list }}"
    
