---
- name: Capstone Automation Playbook
  hosts: all

  roles:
    - role: cp-install
      tag: install

    - role: cp-web
      tag: web

    - role: cp-database

    - role: cp-users
      tag: users

    - role: cp-firewall
      tag: firewall



  tasks:
  - debug:
      msg: "Done perfectly on {{ ansible_distribution }}"

